name: Block-Physics
main: me.hypercodec.physics.BlockPhysics
version: 1.8
author: HyperCodec
api-version: 1.21.4
description: "Makes blocks act like sand and gravel"

permissions:
  blockphysics.*:
    blockphysics.shiftclick: true
    blockphysics.changegrapgics: true

  blockphysics.shiftclick:
    default: true

  blockphysics.changegraphics:
    default: true

commands:
  explosionparticles:
    usage: /explosionparticles <enable|disable>
    description: Enables/disables smoke particles from realistic explosions
    permission: blockphysics.changegraphics
    permission-message: §cYou do not have permission to use this command
    aliases:
      - ep